[workspace]
resolver = "2"
members = [
    "installer",
    # "shared",
    "client",
    # "daemon",
    "workerw_fetcher" # a replacement for the daemon
]
exclude = [
    "research\\downloader"
]

[workspace.dependencies]
winapi = { version = "0.3.9", features = ["winuser"] }
